# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorytype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
