# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_shop', '0002_auto_20170305_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='billing_address',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='mailing_address',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
